#!/bin/bash

TARGET_DIR=$(dirname $0)/
LINK_DIR=~/

TARGET=.vimrc
echo "make link: $TARGET_DIR$TARGET -> $LINK_DIR$TARGET"
ln -s $TARGET_DIR$TARGET $LINK_DIR$TARGET

TARGET=_gvimrc
echo "make link: $TARGET_DIR$TARGET -> $LINK_DIR$TARGET"
ln -s $TARGET_DIR$TARGET $LINK_DIR$TARGET

TARGET=.vim
echo "make link: $TARGET_DIR$TARGET -> $LINK_DIR$TARGET"
ln -s $TARGET_DIR$TARGET $LINK_DIR$TARGET

