gui:
  language: en
  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true

git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
    - pager: delta --dark --paging=never --line-numbers --side-by-side

os:
  edit: "nvim"
  editAtLine: "nvim +{{line}} {{filename}}"

refresher:
  refreshInterval: 30
