gui:
  language: en
  nerdFontsVersion: "3"
  showFileTree: true
  showIcons: true

git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers
    - pager: delta --dark --paging=never --line-numbers --side-by-side

os:
  editPreset: "nvim"

refresher:
  refreshInterval: 30
